name = "BayesBSpline"
uuid = "474088e2-117f-41f8-ba70-ede6f8f1320f"
authors = ["Oskar HÃ¸gberg Simensen"]
version = "1.0.0-DEV"

[deps]
AbstractMCMC = "80f14c24-f653-4e6a-9b94-39d6b0f70001"
BSplineKit = "093aae92-e908-43d7-9660-e50ee39d5a0a"
BridgeSampling = "0eb5b53f-ba9a-4031-a8e1-d982133745c7"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MCMCChains = "c7f686f2-ff18-58e9-bc7b-31028e88f75d"
Memoization = "6fafb56a-5788-4b4e-91ca-c0cea6611c73"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
PolyaGammaHybridSamplers = "c636ee4f-4591-4d8c-9fae-2dea21daa433"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsAPI = "82ae8749-77ed-4fe6-ae5f-f523153014b0"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
